-- AlterTable
ALTER TABLE "City" ADD COLUMN "province" TEXT;
ALTER TABLE "City" ADD COLUMN "lat" DOUBLE PRECISION;
ALTER TABLE "City" ADD COLUMN "lng" DOUBLE PRECISION;
ALTER TABLE "City" ALTER COLUMN "isActive" SET DEFAULT false;
