export enum NotificationKind {
  NEW_APPLICATION = 'NEW_APPLICATION',
  PARTICIPATION_STATUS = 'PARTICIPATION_STATUS',
  EVENT_CANCELLED = 'EVENT_CANCELLED',
  NEW_CHAT_MESSAGE = 'NEW_CHAT_MESSAGE',
  EVENT_REMINDER = 'EVENT_REMINDER',
  NEW_EVENT_IN_CITY = 'NEW_EVENT_IN_CITY',
  REPRIMAND = 'REPRIMAND',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  PAYMENT_CANCELLED = 'PAYMENT_CANCELLED',
}
