export enum WalletTransactionType {
  TOPUP = 'TOPUP',
  EVENT_FEE = 'EVENT_FEE',
  EVENT_REFUND = 'EVENT_REFUND',
  EVENT_CREATION_FEE = 'EVENT_CREATION_FEE',
  ADMIN_CREDIT = 'ADMIN_CREDIT',
  ADMIN_DEBIT = 'ADMIN_DEBIT',
}
