export const FAKE_USERS_MIN_FREE_SLOTS_BUFFER_DEFAULT = 3;
export const FAKE_USERS_DEFAULT_TARGET_OCCUPANCY = 35;
export const FAKE_USERS_FINAL_CLEANUP_HOURS_DEFAULT = 12;

// Aliases for backward compatibility
export const FAKE_USERS_MIN_FREE_SLOTS_BUFFER = FAKE_USERS_MIN_FREE_SLOTS_BUFFER_DEFAULT;
export const FAKE_USERS_FINAL_CLEANUP_HOURS = FAKE_USERS_FINAL_CLEANUP_HOURS_DEFAULT;
