import { render } from '@react-email/render';
import React from 'react';
// @react-email/render dynamically imports react-dom/server at render time.
// This explicit import ensures react-dom is included in the production package.json
// generated by Webpack (otherwise pnpm install --prod in Docker skips it).
import 'react-dom';

export async function renderEmail(element: React.ReactElement): Promise<{
  html: string;
  text: string;
}> {
  const [html, text] = await Promise.all([render(element), render(element, { plainText: true })]);
  return { html, text };
}
